config/routes.rb
Rails.application.routes.draw do
  get 'login' =>  'user_sessions#new', :as => :login
  post 'login' =>  'user_sessions#create'
  delete 'logout' =>  'user_sessions#destroy', :as => :logout

  root 'user_sessions#new'
  resources :tasks
  resources :users, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)

    if @task.save
      redirect_to @task, success: "作成に成功しました"
    else
      flash.now[:danger] = "作成に失敗しました"
      render :new
    end
  end

  def index
    @tasks = current_user.tasks
  end

  def show
    @task = current_user.tasks.find(params[:id])
  end

  def edit
    @task = current_user.tasks.find(params[:id])
  end

  def update
    @task = current_user.tasks.find(params[:id])

    if @task.update(task_params)
      redirect_to @task, success: "変更に成功しました"
    else
      flash.now[:danger] = "変更に失敗しました"
      render :edit
    end
  end

  def destroy
    @task = current_user.tasks.find(params[:id])

    @task.destroy
    redirect_to tasks_path, success: "削除しました"
  end

  private

  def task_params
    params.require(:task).permit(:title, :text)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to tasks_path, success: "ログインしました"
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    logout
    redirect_to login_path, success: "ログアウトしました"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, success: "新規作成に成功しました"
    else
      flash.now[:danger] = "新規作成に失敗しました"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <p class="alert alert-<%= key %>"><%= value %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= link_to 'ログアウト', logout_path, method: :delete %>
    <% else%>
      <%= link_to '新規登録', new_user_path %>
      <%= link_to 'ログイン', login_path %>
    <% end%>
    <%= render partial: 'layouts/flash' %>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_with model: @task, local: true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :text %>
  <%= f.text_area :text %>

  <%= f.submit %>
<% end %>

<%= link_to "タスク一覧へ", tasks_path %>
<%= link_to "戻る", tasks_path %>

app/views/tasks/index.html.erb
<p>
<% @tasks.each do |task|%>
  <%= link_to task do %>
    <%= task.title %>
    <%= link_to "編集", edit_task_path(task) %>
    <%= link_to "削除", task, method: :delete%>
  <% end %>
<% end %>
</p>

<%= link_to "新規作成", new_task_path %>

app/views/tasks/new.html.erb
<%= form_with model: @task, local: true do |f| %>
  <%= render 'layouts/error_messages', object: f.object %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :text %>
  <%= f.text_area :text %>

  <%= f.submit %>
<% end %>

<%= link_to "一覧ページへ", tasks_path %>

app/views/tasks/show.html.erb
<p>title: <%= @task.title %></p>
<p>text: <%= @task.text %></p>

<%= link_to "編集", edit_task_path%>
<%= link_to "戻る", tasks_path %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<%= form_with model: @user, local: true do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit %>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |f|%>
  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<%= form_with model: @user, local: true do |f|%>
  <%= render 'layouts/error_messages', object: f.object%>
  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>